language: ruby
sudo: false
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby-9.1.16.0
gemfile:
  - gemfiles/activesupport3.gemfile
  - gemfiles/activesupport4.gemfile
  - gemfiles/activesupport5.gemfile
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/activesupport5.gemfile
    - rvm: 2.0
      gemfile: gemfiles/activesupport5.gemfile
    - rvm: 2.1
      gemfile: gemfiles/activesupport5.gemfile
    - rvm: 2.2
      gemfile: gemfiles/activesupport5.gemfile
    - rvm: jruby-9.1.16.0
      gemfile: gemfiles/activesupport3.gemfile
